const state = { discovery: null };
const el = Object.fromEntries([
    "settings_state","auto_advance_enabled","transition_timeout_s","scraping_interval","scraping_method",
    "save_settings","auto_advance_hint","autodetect","save_devices","camera_devices","scale_devices",
    "atlas_devices","discovery_errors","restart_notice","toast"
].map(id => [id, document.getElementById(id)]));

function esc(value){return String(value ?? "").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
async function json(url, options={}){const r=await fetch(url,options);let p=null;try{p=await r.json()}catch(_){ }if(!r.ok)throw new Error(p?.detail||`${r.status} ${r.statusText}`);return p}
function toast(message){el.toast.textContent=message;el.toast.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.toast.classList.remove("show"),3000)}
function updateAutoHint(){el.transition_timeout_s.disabled=!el.auto_advance_enabled.checked;el.auto_advance_hint.textContent=el.auto_advance_enabled.checked?"After a stage ends, the next stage starts automatically after this delay unless the operator starts it sooner or pauses.":"Automatic advance is disabled. Transitions wait indefinitely for the operator to start the next stage."}
async function load(){const p=await json("/api/digiflot/settings");el.settings_state.textContent=p.state||"Idle";const o=p.orchestration||{};el.auto_advance_enabled.checked=Boolean(o.auto_advance_enabled);el.transition_timeout_s.value=o.transition_timeout_s ?? 30;el.scraping_interval.value=o.scraping_interval ?? 5;el.scraping_method.value=o.scraping_method||"audio";updateAutoHint()}
function deviceStatus(item){if(item.configured&&item.detected)return ["Configured","configured"];if(item.configured&&!item.detected)return ["Configured / offline","offline"];if(item.detected)return ["Detected","new"];return ["Unavailable","offline"]}
function row(kind,item,label,detail,selectable=true){const [status,cls]=deviceStatus(item);const key=kind==="camera"?item.id:kind==="scale"?item.port:item.address;return `<label class="device-row"><input class="device-select" data-kind="${kind}" data-key="${esc(key)}" type="checkbox" ${(!selectable||item.configured||!item.detected)?"disabled":""} ${selectable&&!item.configured&&item.detected?"checked":""}><span><strong>${esc(label)}</strong><small>${esc(detail)}</small></span><span class="device-status ${cls}">${status}</span></label>`}
function render(){const d=state.discovery;if(!d)return;el.camera_devices.innerHTML=(d.cameras||[]).map(item=>row("camera",item,item.config?.name||item.model||`Camera ${item.id}`,`${item.sensor_resolution?.join(" × ")||"Resolution unknown"}${item.max_fps?` · max ${Number(item.max_fps).toFixed(1)} fps`:""}`,true)).join("")||'<p class="muted">No cameras detected.</p>';el.scale_devices.innerHTML=(d.scales||[]).map(item=>row("scale",item,item.config?.name||item.port,`${item.description||"Serial device"}${item.sample?` · ${item.sample}`:""}`,Boolean(item.probable_scale))).join("")||'<p class="muted">No serial devices detected.</p>';el.atlas_devices.innerHTML=(d.atlas||[]).map(item=>row("atlas",item,item.config?.name||item.name||item.type||`0x${Number(item.address).toString(16)}`,`Address ${item.address} · ${item.type||"EZO"}`,true)).join("")||'<p class="muted">No Atlas EZO sensors detected at known addresses.</p>';const errors=d.errors||[];el.discovery_errors.hidden=!errors.length;el.discovery_errors.innerHTML=errors.map(x=>`<div><strong>${esc(x.source)}</strong>: ${esc(x.error)}</div>`).join("");el.save_devices.disabled=!document.querySelector('.device-select:not(:disabled):checked')}
function selected(){const out={cameras:[],scales:[],atlas:[],atlas_bus:state.discovery?.atlas_bus??1};document.querySelectorAll('.device-select:checked:not(:disabled)').forEach(box=>{const kind=box.dataset.kind;const key=box.dataset.key;const list=kind==="camera"?state.discovery.cameras:kind==="scale"?state.discovery.scales:state.discovery.atlas;const item=list.find(x=>String(kind==="camera"?x.id:kind==="scale"?x.port:x.address)===String(key));if(item)out[kind==="camera"?"cameras":kind==="scale"?"scales":"atlas"].push(item)});return out}
el.auto_advance_enabled.addEventListener("change",updateAutoHint);
el.save_settings.addEventListener("click",async()=>{el.save_settings.disabled=true;try{await json("/api/digiflot/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({auto_advance_enabled:el.auto_advance_enabled.checked,transition_timeout_s:Number(el.transition_timeout_s.value),scraping_interval:Number(el.scraping_interval.value),scraping_method:el.scraping_method.value})});toast("Settings saved.")}catch(e){toast(e.message)}finally{el.save_settings.disabled=false}});
el.autodetect.addEventListener("click",async()=>{el.autodetect.disabled=true;el.autodetect.textContent="Detecting…";try{state.discovery=await json("/api/digiflot/devices/discover",{method:"POST"});render();toast("Device scan complete.")}catch(e){toast(e.message)}finally{el.autodetect.disabled=false;el.autodetect.textContent="Auto-detect devices"}});
document.addEventListener("change",e=>{if(e.target.classList?.contains("device-select"))el.save_devices.disabled=!document.querySelector('.device-select:not(:disabled):checked')});
el.save_devices.addEventListener("click",async()=>{const payload=selected();el.save_devices.disabled=true;try{const result=await json("/api/digiflot/devices/save",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});el.restart_notice.hidden=!result.restart_required;toast(result.changed?"Device configuration saved.":"No new devices selected.");state.discovery=await json("/api/digiflot/devices/discover",{method:"POST"});render()}catch(e){toast(e.message)}finally{if(state.discovery)render()}});
load().catch(e=>toast(e.message));
